[package]
name = "neuronet"
version = "0.1.0"
authors = ["Zander Baker <zanderbaker100@gmail.com>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.7.1", features = ["router", "html"] }
console_error_panic_hook = "0.1"
rand = "0.10.0"
getrandom = { version = "0.4.1", features = ["wasm_js"] }

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
