// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "neuronet";





        [DllImport(__DllName, EntryPoint = "destroy_byte_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void destroy_byte_buffer(ByteBuffer buffer);

        [DllImport(__DllName, EntryPoint = "destroy_neuron_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void destroy_neuron_buffer(NeuronBuffer buffer);

        [DllImport(__DllName, EntryPoint = "destroy_synapse_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void destroy_synapse_buffer(SynapseBuffer buffer);

        [DllImport(__DllName, EntryPoint = "create_event_container", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern EventContainer* create_event_container();

        [DllImport(__DllName, EntryPoint = "destroy_event_container", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void destroy_event_container(EventContainer* container);

        [DllImport(__DllName, EntryPoint = "clear_events", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void clear_events(EventContainer* container);

        [DllImport(__DllName, EntryPoint = "get_spike_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint get_spike_count(EventContainer* container);

        [DllImport(__DllName, EntryPoint = "get_spike", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SpikeEvent get_spike(EventContainer* container, nuint index);

        [DllImport(__DllName, EntryPoint = "create_stimulus_container", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern StimulusContainer* create_stimulus_container();

        [DllImport(__DllName, EntryPoint = "destroy_stimulus_container", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void destroy_stimulus_container(StimulusContainer* container);

        [DllImport(__DllName, EntryPoint = "get_voltage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double get_voltage(Network* network, Runstate* runstate, uint id);

        [DllImport(__DllName, EntryPoint = "get_threshold", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double get_threshold(Network* network, Runstate* runstate, uint id);

        [DllImport(__DllName, EntryPoint = "set_voltage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_voltage(Network* network, Runstate* runstate, uint id, double voltage);

        [DllImport(__DllName, EntryPoint = "runstate_remove_neuron", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void runstate_remove_neuron(Network* network, Runstate* runstate, uint id);

        [DllImport(__DllName, EntryPoint = "set_current_stimulus", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_current_stimulus(StimulusContainer* stimuli, uint neuron_id, double current);

        [DllImport(__DllName, EntryPoint = "step", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Runstate* step(Network* network, Runstate* runstate, StimulusContainer* stimuli, EventContainer* events);

        [DllImport(__DllName, EntryPoint = "create_network", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Network* create_network();

        [DllImport(__DllName, EntryPoint = "destroy_network", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void destroy_network(Network* network);

        [DllImport(__DllName, EntryPoint = "serialize_network", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ByteBuffer serialize_network(Network* network);

        [DllImport(__DllName, EntryPoint = "deserialize_network", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Network* deserialize_network(byte* data, nuint length);

        [DllImport(__DllName, EntryPoint = "get_neurons", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NeuronBuffer get_neurons(Network* network);

        [DllImport(__DllName, EntryPoint = "get_synapses", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SynapseBuffer get_synapses(Network* network);

        [DllImport(__DllName, EntryPoint = "add_synapse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint add_synapse(Network* network, uint source, uint target, double strength, uint conduction_time);

        [DllImport(__DllName, EntryPoint = "add_integrate_fire_neuron", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint add_integrate_fire_neuron(Network* network, uint refractory_period);

        [DllImport(__DllName, EntryPoint = "add_lif_neuron", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint add_lif_neuron(Network* network, uint refractory_period);

        [DllImport(__DllName, EntryPoint = "add_izhikevich_neuron", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint add_izhikevich_neuron(Network* network, uint refractory_period);

        [DllImport(__DllName, EntryPoint = "network_remove_neuron", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void network_remove_neuron(Network* network, uint id);

        [DllImport(__DllName, EntryPoint = "network_remove_synapse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void network_remove_synapse(Network* network, uint id);

        [DllImport(__DllName, EntryPoint = "get_neuron_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern NeuronModelKind get_neuron_model(Network* network, uint id);

        [DllImport(__DllName, EntryPoint = "network_has_neuron", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool network_has_neuron(Network* network, uint id);

        [DllImport(__DllName, EntryPoint = "network_has_synapse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool network_has_synapse(Network* network, uint id);

        [DllImport(__DllName, EntryPoint = "set_neuron_refractory_period", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_neuron_refractory_period(Network* network, uint id, uint refractory_period);

        [DllImport(__DllName, EntryPoint = "set_synapse_strength", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_synapse_strength(Network* network, uint id, double strength);

        [DllImport(__DllName, EntryPoint = "set_synapse_conduction_time", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_synapse_conduction_time(Network* network, uint id, uint conduction_time);

        [DllImport(__DllName, EntryPoint = "create_runstate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Runstate* create_runstate();

        [DllImport(__DllName, EntryPoint = "clone_runstate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Runstate* clone_runstate(Runstate* runstate);

        [DllImport(__DllName, EntryPoint = "destroy_runstate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void destroy_runstate(Runstate* runstate);

        [DllImport(__DllName, EntryPoint = "set_integrate_fire_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_integrate_fire_state(Runstate* runstate, uint neuron_id, IntegrateFireState state);

        [DllImport(__DllName, EntryPoint = "set_lif_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_lif_state(Runstate* runstate, uint neuron_id, LifState state);

        [DllImport(__DllName, EntryPoint = "set_izhikevich_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_izhikevich_state(Runstate* runstate, uint neuron_id, IzhikevichState state);

        [DllImport(__DllName, EntryPoint = "set_default_integrate_fire_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_default_integrate_fire_state(Runstate* runstate, IntegrateFireState state);

        [DllImport(__DllName, EntryPoint = "set_default_lif_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_default_lif_state(Runstate* runstate, LifState state);

        [DllImport(__DllName, EntryPoint = "set_default_izhikevich_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_default_izhikevich_state(Runstate* runstate, IzhikevichState state);

        [DllImport(__DllName, EntryPoint = "fill_defaults", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fill_defaults(Network* network, Runstate* runstate);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* data;
        public nuint len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct NeuronBuffer
    {
        public uint* data;
        public nuint len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SynapseBuffer
    {
        public uint* data;
        public nuint len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct EventContainer
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SpikeEvent
    {
        public uint neuron_id;
        public int timestamp;
        public double voltage;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct StimulusContainer
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Network
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Runstate
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct IntegrateFireState
    {
        public double voltage;
        public double reset_potential;
        public double threshold;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct LifState
    {
        public double voltage;
        public double resting_potential;
        public double reset_potential;
        public double threshold;
        public double leak_constant;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct IzhikevichState
    {
        public double voltage;
        public double reset_potential;
        public double threshold;
        public double a_var;
        public double b_var;
        public double recovery_var;
        public double d_var;
    }


    internal enum NeuronModelKind : uint
    {
        IntegrateFire,
        LIF,
        Izhikevich,
    }


}
