<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>14</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.8"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.8"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.8"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.8">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="bodong.Avalonia.PropertyGrid" Version="11.3.1.5" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="KdTree" Version="1.4.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
        <PackageReference Include="ReactiveUI" Version="24.0.0-beta.3" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.0" />
        <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
    </ItemGroup>
    <ItemGroup>
        <None Include="../../sim-backend/target/release/libneuronet.dylib" CopyToOutputDirectory="PreserveNewest" Link="libneuronet.dylib" />
    </ItemGroup>
</Project>
